### ISSUE TITLE
Look over changes

### ISSUE THREAD

**Issue by bmschmidt** [massivetexts/compare-tools#11]
Tagging @organisciak 

On this repo, I'm being aggressive about merging straight to master because I don't want us to get too far out of sync. Let me know if that's posing problems. 

I've made several (mildly) breaking changes here:

1. The IDs are now in the vector files.

Rather than use Vectorset[regex(htid)], I use a new method: 
`Vectorset.find_prefix(htid, sep="-")`.
Unlike regex, this is as fast as the normal indexed lookup; and finds everything where the string before the first sep character is equal to htid. This requires upgrading to the newest version of pySRP package.

2. I've moved most of the data-creation methods over from hathi-test-dataset to this one. I've also made vector loading lazy--if a glove vector isn't found, one will be found and written to a new file next to the configfile's specification of glove.bin, with a name like glove634a27364efe.bin. It would be possble to write straight into the binary files, but that wouldn't be thread-safe; so instead the approach now uses any file with the same name format to search for binary vectors. The downside is that you now need a global 'glove300d.bin' file for a local installation.

One notable shot here is that we could now easily align--say--Gutenberg texts against these.

3. Subsequent rebuilds of the vector sets should get run with code from this module that I haven't fully written yet, rather than the stuff in hathi-test-dataset which is now purely a data repository.

**Comment by organisciak** [comment]
Thank you! I've been getting confused about the code left behind in hathi-test-dataset. Please, keep using master.

I'm rebuilding my SRP vectorfiles, so I'll see if it causes trouble.

I'm not sure about #2 - you mean lazy-loading vectors through HTID, or elsewhere? I was thinking about updating that code in a different direction - if there isn't a Vector_file, just create the vector on demand in memory, then leave it for garbage collection.

**Comment by bmschmidt** [comment]
Yeah. If you type `HTID("mdp.123455")` and that doesn't exist in `/wherever/glove_space.bin`, it creates a new file at `/wherever/glove_space-adfasdlfkjasfkhuaslkal.bin` and writes the vectors to there. Future reads check all files with that format; at some point though we'll do garbage collection on them.

**Comment by organisciak** [comment]
I got the vectorization code to run, with a few updates. It looks like there was a fair bit of code in hathi_test_dataset, did you forget to check something in?

I'm currently trying to reconcile imports. Right now a lot of code crashes because 'you must define a resolver' in a config file. I don't think code that's not using EF (e.g. MTAnnoy) _needs_ a resolver, so looking to disentangle what gets imported where.

**Comment by organisciak** [comment]
Hmm, in some places it makes sense to import the config file, so rather than changing imports, I removed the critical condition where resolver is required.

**Comment by organisciak** [comment]
Okay, further downstream is working. The merge of offset_cache into PySRP wasn't particularly tricky, but I'll keep testing before pushing it. It's *slow* without it, we'll have to keep that code for when we scale up.

**Comment by organisciak** [comment]
I think I can close this and we'll adapt as we go along.

**Comment by organisciak** [comment]
Following up. I'm uneasy about the auto writing code.

It needs to make many assumptions about how the data was originally created - what the token_kwargs were, the chunk size, where it's saved - and that's a process that is much better done in the place that the original vector_files were created, not in a later class that reads them. I much, _much_ prefer that you catch that error in your code if you need to and follow up _outside_ the library. I'm worried about a) obfuscating and black-boxing change operations (e.g. ending up with a vector_file that had 5k word chunks and suddenly has 10k word ones), b) changing the scope of a read-and-parse class c) hardcoding choices that subsequently funnel applied work into wrangling with the library rather than the application.

Does that make sense? If you'd like to build your vector_files in this way, I can write you a script that catches those errors external to HTID. For now, I temporarily commented out the code.

**Comment by organisciak** [comment]
Of course, this is our own code base so we can do whatever we want. Another option is to move it to a non-private method (`HTID.get_vec_or_write`, perhaps?) that is clear what it's doing and takes all the appropriate parameters as arguments.

**Comment by bmschmidt** [comment]
Yeah, I get the danger argument here. Just to briefly explain the thinking:

1. I have not actually cleared out hathi-test-dataset of code; I meant to say that I've copied the methods and was extending them here, abandoning the old versions. One reason it makes sense for these methods to live inside HTID is that these aren't things specific to the test data. And we want smaller portions of this to be a little bit reproducible.

2. Definitely the caching methods here are not especially robust. But I think this is philosophically in the same place as your chunked parquet cache; we've just settled on 10,000 word chunks and 'ends' chunking, so I don't think the double versions issue is all that likely.

3. There definitely still should be a process to build up all the chunks. It should just be a python script in this repo. I think it makes sense for that to use the HTID class b/c producing vectorizations (even at, say, the page level) is a pretty core function of this research project.

One way to address these concerns might be to have HTID class materialize temporary vectorizations on request (think this was your plan earlier?), but have some other python file in this library be the one responsible for writing to disk **using the vectorizations created by HTID**. When called with `__name__=="__main__"`, it would create the vectorizations for a whole long list of ids; when called with some other method, it could do the temporary caching strategy  I personally want inside a try-catch clause.
