### ISSUE TITLE
Cache offset lookups

### ISSUE THREAD

**Issue by bmschmidt** [massivetexts/compare-tools#3]
[stub issue]

Currently this is generated; should be cached for multi-core optimization.

**Comment by organisciak** [comment]
I implemented a [version](https://github.com/bmschmidt/pySRP/commit/af48b95aeb573051598cbafe565e2f90bef8bfe3) with `shelve`, which is nice because it's built into python and the dict-like API makes it easy to handle both dict and cache approaches concurrently. The DB size for the 150k test set files is 1.8G. However, it fails the most basic test for me, which is a quick open for reading a single vector. The following takes 15s for me, which is only half of the 30s it takes to just build the in-memory dict!

```python
with Vector_file('testset.bin', mode='r', offset_cache=True) as vfile:
    vfile['aeu.ark:/13960/t0000s333-0001']
```

Now, I'm updating the code to use `sqlitedict`, a dict-like interface to SQLite. This helps avoid the scaffolding to support SQL statements in pySRP.

 - Pros: the `sqlitedict` version of the above code takes 1-3 milliseconds; the DB is a bit under a 7th of a size. 
 - Cons: initial write is slow (though not _too_ slow) - 11min for the 3.6m vectors in the test set; it adds a dependency, albeit a pure Python one; the value is stored as a string in the DB - an int would be much more efficient, though I wouldn't fork the code unless really necessary.

I avoid saving the cache as JSON or a pickle in the interest of future scale and multiprocessing. A dictionary is stellar and likely can't be improved for performance, but the memory use will be too large when scaling to 7m volumes and multiple processes.

**Comment by organisciak** [comment]
Updated, in https://github.com/bmschmidt/pySRP/tree/offset_cache. I didn't add it to the requirements.txt - it looks like you're trying to avoid dependencies, so maybe a conditional import if you try to use that specific feature?

Regardless, I'll work with the copy out of the branch for the time being.

**Comment by organisciak** [comment]
A small addendum - because SQLite doesn't really care, extending `sqlitedict` to save its values as unencoded ints rather than blobs made no difference.

**Comment by bmschmidt** [comment]
Are you using this feature? It'll have to be extended to the new prefix-lookup syntax.

**Comment by organisciak** [comment]
Yes, I've been using it, I'll try to update it.

**Comment by organisciak** [comment]
Updated. Much smaller index for the prefix database.

**Comment by organisciak** [comment]
Of course, much smaller because of a stupid bug :/ Goodness fixing now.
